// <auto-generated />
using System;
using HealthCatalystAssessment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HealthCatalystAssessment.Migrations
{
    [DbContext(typeof(HealthCatalystAssessmentContext))]
    [Migration("20210620182231_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HealthCatalystAssessment.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("Age")
                        .HasColumnType("tinyint");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd6ebe6c-875e-455a-aa1e-edb1429f93e7"),
                            Address = "Oregon",
                            Age = (byte)30,
                            FirstName = "Hardik",
                            LastName = "Shah"
                        },
                        new
                        {
                            Id = new Guid("024f1c07-4f80-4540-8495-6027e49a8866"),
                            Address = "Carribean",
                            Age = (byte)35,
                            FirstName = "Jack",
                            LastName = "Sparrow"
                        },
                        new
                        {
                            Id = new Guid("6546b18a-62e4-4a48-a5fc-fc4f9171a7d1"),
                            Address = "Hogwarts",
                            Age = (byte)20,
                            FirstName = "Harry",
                            LastName = "Potter"
                        });
                });

            modelBuilder.Entity("HealthCatalystAssessment.Models.User", b =>
                {
                    b.OwnsMany("HealthCatalystAssessment.Models.Interest", "Interests", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Activity")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("UserId", "Id");

                            b1.ToTable("Interest");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.HasData(
                                new
                                {
                                    UserId = new Guid("dd6ebe6c-875e-455a-aa1e-edb1429f93e7"),
                                    Id = new Guid("df96d2af-a5a5-4dec-af24-d7689aa4cb89"),
                                    Activity = "Video Games"
                                },
                                new
                                {
                                    UserId = new Guid("dd6ebe6c-875e-455a-aa1e-edb1429f93e7"),
                                    Id = new Guid("8c82801f-33d2-4ae5-954b-94befe92aaa7"),
                                    Activity = "Biking"
                                },
                                new
                                {
                                    UserId = new Guid("dd6ebe6c-875e-455a-aa1e-edb1429f93e7"),
                                    Id = new Guid("1b5cafd3-c40e-48e8-ab85-1f1a67d04fe3"),
                                    Activity = "Software Development"
                                },
                                new
                                {
                                    UserId = new Guid("024f1c07-4f80-4540-8495-6027e49a8866"),
                                    Id = new Guid("147e22fe-3ca9-4322-9b68-fa09f9bfc814"),
                                    Activity = "Black Pearl"
                                },
                                new
                                {
                                    UserId = new Guid("024f1c07-4f80-4540-8495-6027e49a8866"),
                                    Id = new Guid("c0c064dd-c018-45bf-8cb0-e0435b601518"),
                                    Activity = "Treasure hunting"
                                },
                                new
                                {
                                    UserId = new Guid("024f1c07-4f80-4540-8495-6027e49a8866"),
                                    Id = new Guid("9617799a-7ce2-41f1-bf71-3818c3851834"),
                                    Activity = "Sea Adventures"
                                },
                                new
                                {
                                    UserId = new Guid("6546b18a-62e4-4a48-a5fc-fc4f9171a7d1"),
                                    Id = new Guid("8f6a72a5-5b9b-4655-8db4-1a7adbc340ce"),
                                    Activity = "Quidditch"
                                },
                                new
                                {
                                    UserId = new Guid("6546b18a-62e4-4a48-a5fc-fc4f9171a7d1"),
                                    Id = new Guid("6c5df546-68fa-4d11-a98c-a2869d3f6139"),
                                    Activity = "Magic"
                                },
                                new
                                {
                                    UserId = new Guid("6546b18a-62e4-4a48-a5fc-fc4f9171a7d1"),
                                    Id = new Guid("89e77ce5-b481-4a0b-81ac-718da50d24c7"),
                                    Activity = "Butterbeer"
                                });
                        });

                    b.Navigation("Interests");
                });
#pragma warning restore 612, 618
        }
    }
}
